version: "3"
name: server-tpl
services:
  server:
    env_file: .env
    image: server/tpl
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev__server-tpl
    volumes:
      - .:/app
      - ./node_modules:/app
      - ./public:/app
    ports:
      - 7711:7711
