version: "3"
name: server-tpl
services:
  server:
    image: server/tpl
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: dev__server-tpl
    volumes:
      - .:/app
      - ./src:/app
      - ./node_modules:/app
    ports:
      - 3500:3000
